### PR TITLE
feat: merged new commits from parent branch

### PR DESCRIPTION
**Pull request by mzndako**
Update Exodus forked branch with new commits from the parent branch

### CODE REVIEW

**Comment by bulgakovk** [comment]
Wow so many changes :D Can we try to rebase our `master` onto `their` master instead? Exodus has been merged to the upstream repository so I guess there shouldn't be any conflicts.

**Review by timlanahan — COMMENTED** [review]
hmm, agree w/ kirll.  is there an easier way to sync the fork?  maybe not

**Comment by mzndako** [comment]
> Wow so many changes :D Can we try to rebase our `master` onto `their` master instead? Exodus has been merged to the upstream repository so I guess there shouldn't be any conflicts.

The parent repo had more than 240 commits ahead of Exodus forked one. That's why the commits are many which was resulting in dealing with too many conflicts when rebasing. Been able to rebase now though

**Comment by mzndako** [comment]
After rebasing I noticed all the commits diff now carry my identity as co-authored. Since `feat/exodus-extension` has already been rebased against the parent repo (`/cosmology-tech/cosmos-kit`). I guess it's fine for us to simply merge this branch into `main` instead of rebasing. 

Thought?

**Comment by bulgakovk** [comment]
No objections as long as it keeps us up-to-date

**Comment by mzndako** [comment]
Reverted back to merging (cleaner) instead of rebasing

**Review by bulgakovk — APPROVED** [review]
utACK

**Pull request merged**
